categories = {
    'Sport': [
        'Brydż',
        'Szachy',
        'Siatkówka',
        'Krykiet',
        'Bilard :P',
    ],
    'Muzyka': [
        'Techno',
        'Metal',
        'Country',
        'Hip-Hop',
    ],
    'Historia': [
        'Wystawy historyczne',
        'Rekonstrukcje',
    ],
    'Sztuka': [
        'Wystawy',
        'Galerie',
        'Teatr',
        'Opera',
    ],
}

tags = [
    'kuchnia polska',
    'kuchnia francuska',
    'kuchnia włoska',
    'kuchnia chińska',
    'kuchnia japońska',
    'kuchnia rosyjska',
    'kuchnia meksykańska',
    'kajaki',
    'gokarty',
    'paintball',
    'basen',
    'las',
    'plaża',
    'krowy',
    'konie',
    'dziwki',
    'jazz',
    'pop',
    'klasyczna',
    'rock',
    'kabaret',
]

addresses = {
    'streets': [
        'Zgodna 2/3',
        'Krówki 5/8',
        'Dziady 1/1',
        'Chłopy 2a',
        'Dziewki 9',
        'Lemoniady 42',
    ],
    'cities': [
        {'name': 'Wrocław', 'lat': 51, 'lon': 17},
        {'name': 'Kraków', 'lat': 50, 'lon': 20},
        {'name': 'Łódź', 'lat': 51.8, 'lon': 19.5},
        {'name': 'Warszawa', 'lat': 52.2, 'lon': 21},
        {'name': 'Szczecin', 'lat': 53.5, 'lon': 14.5},
        {'name': 'Kalisz', 'lat': 51.7, 'lon': 18.1},
        {'name': 'Gdańsk', 'lat': 54.4, 'lon': 18.6},
        {'name': 'Poznań', 'lat': 52.4, 'lon': 16.9},
        {'name': 'Lublin', 'lat': 51.2, 'lon': 22.6},
        {'name': 'Białystok', 'lat': 53.1, 'lon': 23.2}
    ],
}

vendors = {
    'names': [
        'PKN Orlen',
        'GK Grupy Lotos',
        'PGE Polska Grupa Energetyczna',
        'Jeronimo Martins Polska',
        'GK PGNiG',
        'GK Tauron Polska Energia',
        'KGHM Polska Miedź',
        'Grupa Eurocash',
        'Metro Group w Polsce',
        'GK Orange Polska',
        'Fiat Auto Poland',
        'BP Europa SE Oddział w Polsce',
        'GK Energa',
        'Kompania Węglowa',
        'GK Enea',
        'Philip Morris International w Polsce',
        'Volkswagen Poznań',
        'Orlen Paliwa',
        'GK Jastrzębskiej Spółki Węglowej',
        'Lidl Polska Sklepy Spożywcze',
        'Państwowe Gospodarstwo Leśne Lasy Państwowe',
        'Carrefour w Polsce',
        'Shell Polska',
        'GK Polkomtel',
        'GK Grupy Azoty',
        'Polska Telefonia Cyfrowa',
        'Polskie Sieci Elektroenergetyczne',
        'GK Pelion',
        'Auchan Polska',
        'Samsung Electronics Polska',
        'GK Synthos',
        'GK Budimex',
        'Imperial Tobacco Polska',
        'GK Neuca',
        'GK Asseco Poland',
        'Statoil Fuel & Retail Polska',
        'LG Electronics Wrocław',
        'GK Boryszew',
        'GK Farmacol',
        'GK AB',
        'GK Specjał',
        'Grupa Muszkieterów',
        'PKP Cargo',
        'Grupa Can-Pack',
        'GK GlaxoSmithKline Pharmaceuticals',
        'Philips Lighting Poland',
        'GK Kompania Piwowarska',
        'Grupa Chemiczna Ciech',
        'LG Electronics Mława',
        'Grupa Cargill w Polsce',
        'Grupa Skanska',
        'PKP Polskie Linie Kolejowe',
        'Rossmann Supermarkety Drogeryjne Polska',
        'Kolporter',
        'GK Polimex-Mostostal',
        'KGHM Metraco',
        'Volkswagen Motor Polska',
        'Grupaint-Gobain w Polsce',
        'Zakłady Azotowe Puławy',
        'Strabag',
        'GK ABC Data',
        'Tele-Fonika Kable',
        'Katowicki Holding Węglowy',
        'EdF Energia',
        'Faurecia w Polsce',
        'POLOmarket',
        'GK Grupy Żywiec',
        'GK Action',
        'Fiat Powertrain Technologies Poland',
        'P4 (Play)',
        'Totalizator Sportowy',
        'BSH Sprzęt Gospodarstwa Domowego',
        'Selgros',
        'Grupa Anwil',
        'Electrolux Poland',
        'JTI Polska',
        'Grupa Valeo',
        'Żabka Polska',
        'PLL LOT',
        'Indesit Company Polska',
        'Orlen PetroTank',
        'Grupa Bumar',
        'GK NFI Empik Media&Fashion',
        'PKP Energetyka',
        'GK LPP',
        'SM Mlekpol',
        'GK Mostostal Warszawa',
        'Unilever Polska',
        'CMC Poland',
        'Grupa Mlekovita',
        'GK Inter Cars',
        'Grupa Maspex Wadowice',
        'GK Sokołów',
        'EdF Paliwa',
        'Ferrero Polska',
        'Nestle Polska',
        'GK Cyfrowy Pot',
        'E.Leclerc Polska',
    ],
    'descriptions': [
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, dicta, "
        "quasi itaque ullam in quo architecto molestias non pariatur reiciendis"
        " fugaepe sint minus. Magni vero eius modi dolore deleniti.",
        'ashdjhas jkdh ajkhsd jkahsd kj',
    ],
}

contacts = [
    {  # www
        'type': 1,
        'values': [
            'www.asd.com',
            'www.kgfmdg.com',
            'www.fgkjdfg.com',
            'www.ass-assssd.com',
            'www.dupa.com',
        ],
    },
    {  # email
        'type': 2,
        'values': [
            'asd@asdd',
            'cv@cvbcvsdd',
            '123@asdd',
            'vv@asvvvcbcvb.reg',
            'zzz@azzzzzz.zad',
        ],
    },
    {  # tel
        'type': 3,
        'values': [
            '132-132-132',
            '123-123-123',
            '637-637-637',
            '683-683-683',
            '348-348-348',
        ],
    },
    {  # fax
        'type': 4,
        'values': [
            '+44-208-1234567',
            '+12-228-8757566',
            '+67-118-3482734',
            '+34-658-6537856',
            '+82-287-5738975',
        ],
    },
    {  # facebook
        'type': 5,
        'values': [
            'www.facebook.com/asd'
            'www.facebook.com/gdgdfg'
            'www.facebook.com/dfgfgew'
            'www.facebook.com/sdfsdf'
            'www.facebook.com/ert-ert'
        ],
    },
]

contact_descriptions = [
    '',
    'blabla',
    'CEO',
]
