categories = {
    'Sport': [
        'Brydż',
        'Szachy',
        'Siatkówka',
        'Krykiet',
        'Bilard :P',
    ],
    'Muzyka': [
        'Techno',
        'Metal',
        'Country',
        'Hip-Hop',
    ],
    'Historia': [
        'Wystawy historyczne',
        'Rekonstrukcje',
    ],
    'Sztuka': [
        'Wystawy',
        'Galerie',
        'Teatr',
        'Opera',
    ],
}

tags = [
    'kuchnia polska',
    'kuchnia francuska',
    'kuchnia włoska',
    'kuchnia chińska',
    'kuchnia japońska',
    'kuchnia rosyjska',
    'kuchnia meksykańska',
    'kajaki',
    'gokarty',
    'paintball',
    'basen',
    'las',
    'plaża',
    'krowy',
    'konie',
    'dziwki',
    'jazz',
    'pop',
    'klasyczna',
    'rock',
    'kabaret',
]

addresses = {
    'streets': [
        'Zgodna 2/3',
        'Krówki 5/8',
        'Dziady 1/1',
        'Chłopy 2a',
        'Dziewki 9',
        'Lemoniady 42',
    ],
    'cities': [
        {'name': 'Wrocław', 'lat': 51, 'lon': 17},
        {'name': 'Kraków', 'lat': 50, 'lon': 20},
        {'name': 'Łódź', 'lat': 51.8, 'lon': 19.5},
        {'name': 'Warszawa', 'lat': 52.2, 'lon': 21},
        {'name': 'Szczecin', 'lat': 53.5, 'lon': 14.5},
        {'name': 'Kalisz', 'lat': 51.7, 'lon': 18.1},
        {'name': 'Gdańsk', 'lat': 54.4, 'lon': 18.6},
        {'name': 'Poznań', 'lat': 52.4, 'lon': 16.9},
        {'name': 'Lublin', 'lat': 51.2, 'lon': 22.6},
        {'name': 'Białystok', 'lat': 53.1, 'lon': 23.2}
    ],
}

vendors = {
    'names': [
        'PKN Orlen SA',
        'GK Grupy Lotos SA',
        'PGE Polska Grupa Energetyczna SA',
        'Jeronimo Martins Polska SA',
        'GK PGNiG SA',
        'GK Tauron Polska Energia SA',
        'KGHM Polska Miedź SA',
        'Grupa Eurocash SA',
        'Metro Group w Polsce',
        'GK Orange Polska (Telekomunikacja Polska SA)',
        'Fiat Auto Poland SA',
        'BP Europa SE Oddział w Polsce',
        'GK Energa SA',
        'Kompania Węglowa SA',
        'GK Enea SA',
        'Philip Morris International w Polsce',
        'Volkswagen Poznań Sp. z o.o.',
        'Orlen Paliwa Sp. z o.o.',
        'GK Jastrzębskiej Spółki Węglowej SA',
        'Lidl Polska Sklepy Spożywcze Sp. z o.o. Sp. k.',
        'Państwowe Gospodarstwo Leśne Lasy Państwowe',
        'Carrefour w Polsce',
        'Shell Polska Sp. z o.o.',
        'GK Polkomtel SA',
        'GK Grupy Azoty SA',
        'Polska Telefonia Cyfrowa SA (T-Mobile)',
        'Polskie Sieci Elektroenergetyczne SA',
        'GK Pelion SA',
        'Auchan Polska Sp. z o.o.',
        'Samsung Electronics Polska Sp. z o.o.',
        'GK Synthos SA',
        'GK Budimex SA',
        'Imperial Tobacco Polska SA',
        'GK Neuca SA',
        'GK Asseco Poland SA',
        'Statoil Fuel & Retail Polska Sp. z o.o.',
        'LG Electronics Wrocław Sp. z o.o.',
        'GK Boryszew SA',
        'GK Farmacol SA',
        'GK AB SA',
        'GK Specjał',
        'Grupa Muszkieterów',
        'PKP Cargo SA',
        'Grupa Can-Pack SA',
        'GK GlaxoSmithKline Pharmaceuticals SA',
        'Philips Lighting Poland SA',
        'GK Kompania Piwowarska SA',
        'Grupa Chemiczna Ciech',
        'LG Electronics Mława Sp. z o.o.',
        'Grupa Cargill w Polsce',
        'Grupa Skanska SA',
        'PKP Polskie Linie Kolejowe SA',
        'Rossmann Supermarkety Drogeryjne Polska Sp. z o.o.',
        'Kolporter Sp. z o.o. S.K.A.',
        'GK Polimex-Mostostal SA',
        'KGHM Metraco SA',
        'Volkswagen Motor Polska Sp. z o.o.',
        'Grupa Saint-Gobain w Polsce',
        'Zakłady Azotowe Puławy SA',
        'Strabag Sp. z o.o.',
        'GK ABC Data SA',
        'Tele-Fonika Kable Sp. z o.o. S.K.A.',
        'Katowicki Holding Węglowy SA',
        'EdF Energia Sp. z o.o.',
        'Faurecia w Polsce',
        'POLOmarket Sp. z o.o.',
        'GK Grupy Żywiec SA',
        'GK Action SA',
        'Fiat Powertrain Technologies Poland Sp. z o.o.',
        'P4 Sp. z o.o. (Play)',
        'Totalizator Sportowy Sp. z o.o.',
        'BSH Sprzęt Gospodarstwa Domowego Sp. z o.o.',
        'Selgros Sp. z o.o.',
        'Grupa Anwil SA',
        'Electrolux Poland Sp. z o.o.',
        'JTI Polska Sp. z o.o.',
        'Grupa Valeo',
        'Żabka Polska Sp. z o. o.',
        'PLL LOT SA',
        'Indesit Company Polska Sp. z o.o.',
        'Orlen PetroTank Sp. z o.o.',
        'Grupa Bumar',
        'GK NFI Empik Media&Fashion SA',
        'PKP Energetyka SA',
        'GK LPP SA',
        'SM Mlekpol',
        'GK Mostostal Warszawa SA',
        'Unilever Polska',
        'CMC Poland Sp. z o.o.',
        'Grupa Mlekovita',
        'GK Inter Cars SA',
        'Grupa Maspex Wadowice',
        'GK Sokołów SA',
        'EdF Paliwa Sp. z o.o.',
        'Ferrero Polska Sp. z o.o.',
        'Nestle Polska SA',
        'GK Cyfrowy Polsat SA',
        'E.Leclerc Polska',
    ],
    'descriptions': [
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, dicta, "
        "quasi itaque ullam in quo architecto molestias non pariatur reiciendis"
        " fuga saepe sint minus. Magni vero eius modi dolore deleniti.",
        'ashdjhas jkdh ajkhsd jkahsd kj',
    ],
}

contacts = [
    {  # www
        'type': 1,
        'values': [
            'www.asd.com',
            'www.kgfmdg.com',
            'www.fgkjdfg.com',
            'www.ass-assssd.com',
            'www.dupa.com',
        ],
    },
    {  # email
        'type': 2,
        'values': [
            'asd@asd.sad',
            'cv@cvbcvsd.sad',
            '123@asd.sad',
            'vv@asvvvcbcvb.reg',
            'zzz@azzzzzz.zad',
        ],
    },
    {  # tel
        'type': 3,
        'values': [
            '132-132-132',
            '123-123-123',
            '637-637-637',
            '683-683-683',
            '348-348-348',
        ],
    },
    {  # fax
        'type': 4,
        'values': [
            '+44-208-1234567',
            '+12-228-8757566',
            '+67-118-3482734',
            '+34-658-6537856',
            '+82-287-5738975',
        ],
    },
    {  # facebook
        'type': 5,
        'values': [
            'www.facebook.com/asd'
            'www.facebook.com/gdgdfg'
            'www.facebook.com/dfgfgew'
            'www.facebook.com/sdfsdf'
            'www.facebook.com/ert-ert'
        ],
    },
]

contact_descriptions = [
    '',
    'blabla',
    'CEO',
]
