#!/bin/bash

NGINX_PIDFILE=$OPENSHIFT_DATA_DIR/nginx/logs/nginx.pid
if [ -f $NGINX_PIDFILE ]; then
    echo 'Stoping nginx'
    $OPENSHIFT_DATA_DIR/nginx/sbin/nginx -s stop
    echo 'nginx stopped'
fi

cd ${OPENSHIFT_REPO_DIR}
echo 'Stopping uwsgi'
uwsgi --stop uwsgi.pid
echo 'uwsgi stopped'
