#!/bin/bash

cd ${OPENSHIFT_REPO_DIR}

if grep -Fxq "production" instance
then
    echo 'production instance'
    INI_FILE=production.ini
    cp .openshift/nginx.conf $OPENSHIFT_DATA_DIR/nginx/conf/nginx.conf
else
    echo 'staging instance'
    INI_FILE=staging.ini
    cp .openshift/nginx-staging.conf $OPENSHIFT_DATA_DIR/nginx/conf/nginx.conf
fi

echo 'Starting uwsgi'
uwsgi $INI_FILE
echo 'uwsgi started'

echo 'Starting nginx'
$OPENSHIFT_DATA_DIR/nginx/sbin/nginx
echo 'nginx started'
