#!/bin/bash

cd ${OPENSHIFT_REPO_DIR}

cp .openshift/nginx.conf $OPENSHIFT_DATA_DIR/nginx/conf/nginx.conf

echo 'Starting uwsgi'
uwsgi production.ini
echo 'uwsgi starter'

echo 'Starting nginx'
$OPENSHIFT_DATA_DIR/nginx/sbin/nginx
echo 'nginx started'
