from collections import namedtuple

Cell = namedtuple('Cell', ['column', 'header', 'field'])
columns_definitions = [
    Cell(column='A', header='Nazwa', field='name'),
    Cell(column='B', header='Opis', field='description'),
    Cell(column='C', header='url opisu', field='contacts'),
    Cell(column='D', header='Kategoria', field='categories'),
    Cell(column='E', header='Podkategoria', field='subcategories'),
    Cell(column='F', header='Ulica', field='street'),
    Cell(column='G', header='Miasto', field='city'),
    Cell(column='H', header='Kod pocztowy', field='postal_code'),
    Cell(column='I', header='www', field='www'),
    Cell(column='J', header='[opis www]', field='www_description'),
    Cell(column='K', header='Dane kontaktowe', field='contacts'),
    Cell(column='L', header='Youtube', field='youtube'),
    Cell(column='M', header='Czy darmowe', field='is_free'),
    Cell(column='N', header='Cena', field='price'),
    Cell(column='O', header='Link do cennika', field='price_list_url'),
    Cell(column='P', header='Ilość uczestników', field='participant_count'),
    Cell(column='Q', header='Ograniczenie wiekowe',
         field='age_restriction'),
    Cell(column='R', header='Galeria', field='gallery'),
    Cell(column='S', header='Facebook', field='facebook'),
    Cell(column='T', header='Dni-godziny', field='available_at'),
    Cell(column='U', header='Współrzędne geograficzne',
         field='coordinates'),
    Cell(column='V', header='Tagi', field='tags'),
    Cell(column='W', header='Logo', field='logo'),
    Cell(column='X', header='Data dodania', field='added_at'),
    Cell(column='Y', header='Data aktualizacji', field='updated_at'),
    Cell(column='Z', header='Promocja', field='promotion'),
    Cell(column='AA', header='Dostępność czasowa',
         field='available_at_date'),
]
